name: blockchain
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^0.4.0+1
  cupertino_icons: ^0.1.2
  firebase:
  firebase_analytics:

flutter_icon:
  android: true
  ios: true
  image_path_android: "/lib/assets/appicon-Android/"
  image_path_ios: "/lib/assets/appIcon-ios/"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
